### ISSUE TITLE
Usage with jest

### ISSUE THREAD

**Issue by revmischa** [chax-at/transactional-prisma-testing#1]
I'm trying to figure out how to use this module with jest

I'm mocking out my lazy prisma client with jest:
```ts
const prismaClient = getPrismaClient()
await truncateAllTables(prismaClient)

const prismaTestingHelper = new PrismaTestingHelper(prismaClient)
let prismaClientProxy = prismaTestingHelper.getProxyClient()

class PrismaClientProxy {
  get() {
    return prismaClientProxy
  }
  get c() {
    return prismaClientProxy
  }
}
jest.unstable_mockModule("@service/repo/client", () => {
  return {
    PrismaClient,
    Prisma,
    prisma: new PrismaClientProxy(),
  }
})
```

But when my test tries to use the proxyClient, it has all of the models inside of the proxy object but they're all `undefined`. Any idea why that might be?

**Comment by Valerionn** [comment]
How does your original `@service/repo/client` look like, and how are you accessing it? Does it work if you mock it with
```ts
jest.unstable_mockModule("@service/repo/client", () => {
  return {
    PrismaClient,
    Prisma,
    prisma: prismaClientProxy,
  }
})
```
(without the separate `PrismaClientProxy` object)?

**Comment by revmischa** [comment]
I have a lazy wrapper around my prisma client

````ts
import type { PrismaClient as PrismaClientType } from "@prisma/client"
import { LazyInstance } from "@selfage/lazy_instance"
import { getPrismaClient } from "./util/getPrismaClient"
import PrismaClientPkg from "@prisma/client"

const { PrismaClient, Prisma } = PrismaClientPkg
export { PrismaClient, Prisma }

// doubly-lazy prisma client :)
class LazyPrismaInstance extends LazyInstance<PrismaClientType> {
  // lazy way to get the lazy instance
  get c() {
    return this.get()
  }
}

export const prisma = new LazyPrismaInstance(getPrismaClient)
```

But I fail to see why it would affect me getting `undefined` for all of the models

**Comment by revmischa** [comment]
The error I get in my test is:
```
    TypeError: Cannot read properties of undefined (reading 'findUnique')
```
Which is like `prisma.user.findUnique` so it's not just undefined when printing

I'll take a look at the example repo

unstable_mockModule is for ESM, and you need to do it **before** async importing (`const { foo } = await import('./myModule')`) the module you're testing for the mocks to work

**Comment by Valerionn** [comment]
I just updated my example repo to use `unstable_mockModule` and it works - so I guess the issue is somehow related to your specific use-case. You could try to call something like
```ts
const prismaClient = getPrismaClient()
await truncateAllTables(prismaClient)

const prismaTestingHelper = new PrismaTestingHelper(prismaClient)
let prismaClientProxy = prismaTestingHelper.getProxyClient()

const user = await prismaClientProxy.user.findUnique(/* ... */);
```
and if this works, then the problem has something to do with the mock. 

If you have a reproduction repo, then I can take a look. But otherwise, I currently don't have an ideas why it wouldn't work in your case.

**Comment by revmischa** [comment]
I'm making the switch to `vitest` because it has better mocking support for ES modules. Thanks for your help
