### ISSUE TITLE
Setting transaction timeout has no effect

### ISSUE THREAD

**Issue by MarcManiez** [chax-at/transactional-prisma-testing#12]
Hello, and thank you for this lovely tool!

I'd like to report what seems to be an issue with increasing the default transaction timeout. I'm a tad short on time to submit a full repo to reproduce this, but here are some key configuration elements:

- Test script: `NODE_ENV=test mocha -r @swc-node/register -r --require src/test/hooks.ts`

```ts
// src/test/hooks.ts

exports.mochaHooks = {
  async beforeEach() {
    await prismaTestingHelper.startNewTransaction({ timeout: 30000 });
  },
  async afterEach() {
    prismaTestingHelper.rollbackCurrentTransaction();
  },
};
```

```ts
// a test file

import { setTimeout } from 'timers/promises';

describe('A module to test', () => {
  it('should not throw due to a transaction timeout issue', async () => {
    await setTimeout(3000); // the default transaction timeout is 2000 ms
  });
});
```

Running the test file above results in the following error message:

```console
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/path/to/test/file.ts)
      at listOnTimeout (node:internal/timers:573:17)
      at processTimers (node:internal/timers:514:7)
```

Let me know if there's any other info I can provide!

**Comment by Valerionn** [comment]
Hey!

You seem to run into Mocha's default test timeout which is 2000ms (compared to Prisma's default 5s transaction timeout). This is also why the error message mentions "tests and hooks" explicitly (Prisma's error message would look a bit different).

Try running your tests with `--timeout 30000` or call `this.timeout(30000)` in the the test itself (as described [here](https://mochajs.org/#test-level))

**Comment by MarcManiez** [comment]
Good call, that's exactly what's going on!

I was lead astray by this error (from an actual test) indicating that the a transaction had ended:

```
Transaction API error: Transaction already closed: A query cannot be executed on a transaction that was rolled back.
```

I assumed it was because the transaction params weren't being applied properly, but I now understand that mocha timed out and ran the `afterEach` clause of `hooks.ts`, which had the same effect of closing the transaction.

Thank you for for your patience. All the best!
