### ISSUE TITLE
When using the `then` syntax, the output of the `onFulfilled` callback is discarded

### ISSUE THREAD

**Issue by matthieu-foucault** [chax-at/transactional-prisma-testing#13]
When using the `transactional-prisma-testing` helper in our tests, the following code patterns do not return the expected result: 

```js
const myTransformedData = await prisma.myTable.findMany().then(data => data.map(transformData))
```

I would expect `myTransformedData` to be the output of `data.map(transformData)`, but what I get instead is the raw data from `findMany()`.

While mixing the `await` and `then` syntax is a debatable choice, it is somewhat pervasive in our code base and I would prefer finding a fix here if possible.

Taking a brief look at the code, should this (and the other `return` below)
https://github.com/chax-at/transactional-prisma-testing/blob/69ef6452a28f7fcf79754a94c58fa1e84c749f29/src/prisma.testing.helper.ts#L74-L75

be `return resolve(value as any)` instead?

Happy to provide a reproduction and/or submit a PR if help is needed.

PS: Love this package, this has been incredibly helpful in having efficient tests in our project and IMO it should be officially supported by Prisma

**Comment by Valerionn** [comment]
Hey!

Thank you for your bug report and according to my tests, your proposed code changes should fix this issue.

I have just published a new version, `1.2.1`, which should fix this issue. If you're still encountering problems, then please just re-open this issue (I've only tested this with a simple scenario as we're not using this pattern in our code base).

**Comment by Valerionn** [comment]
Fun Fact: I don't really know how exactly `await` interacts with a custom object with a `then()` function (like I'm using here) - but there are some weird interactions:
```
let promiseFixed = { then: async function(resolve) { return resolve(7); } }
let promiseBugged = { then: async function(resolve) { resolve(7); return 5; } }

await promiseFixed; // returns 7
await promiseFixed.then(x => x); // returns 7
await promiseFixed.then(_ => 3) // returns 3

await promiseBugged; // returns 7 (ignores the return value, uses the value from resolve function)
await promiseBugged.then(x => x); // returns 5 (uses the value from return)
await promiseBugged.then(_ => 3);  // returns 5 (because it uses the return value)
```

I hope all special cases are now fixed with the `return resolve(...)` :)

**Comment by matthieu-foucault** [comment]
Thanks for the quick fix and release! I can confirm it works as expected now.
